apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pqrs-ingress
  namespace: pqrs-saas
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "pqrs-api"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - pqrs.jaramc.dev
      secretName: pqrs-tls-secret
    - hosts:
        - support.jaramc.dev
      secretName: support-tls-secret
    - hosts:
        - triage.jaramc.dev
      secretName: triage-tls-secret
  rules:
    # 1. Panel de Agentes (Dashboard React)
    - host: pqrs.jaramc.dev
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: pqrs-api
                port:
                  number: 8080
          - path: /hubs
            pathType: Prefix
            backend:
              service:
                name: pqrs-api
                port:
                  number: 8080
          - path: /swagger
            pathType: Prefix
            backend:
              service:
                name: pqrs-api
                port:
                  number: 8080
          - path: /pqrs-widget.js
            pathType: Prefix
            backend:
              service:
                name: pqrs-api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pqrs-client
                port:
                  number: 80

    # 2. Portal Demo de Soporte y Widget CDN
    - host: support.jaramc.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pqrs-api
                port:
                  number: 8080

    # 3. Backend API REST, Swagger y Motor de Triaje / RAG
    - host: triage.jaramc.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pqrs-api
                port:
                  number: 8080
