services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      POSTGRES_DB: pqrs
      POSTGRES_USER: pqrs_app
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pqrs_app -d pqrs"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  api:
    build:
      context: .
      dockerfile: src/PQRS.Api/Dockerfile
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=pqrs;Username=pqrs_app;Password=${POSTGRES_PASSWORD}
      - JwtSettings__SecretKey=super_secret_and_long_key_with_at_least_256_bits_length_for_hmac_sha256!
      - JwtSettings__Issuer=PQRS.SaaS.Platform
      - JwtSettings__Audience=PQRS.SaaS.Clients
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

volumes:
  postgres_data: