import { ArrowUpRight } from 'lucide-react';
import type { Ticket, TicketPriority, TicketSentiment } from '../types';
import { TicketCard } from './TicketCard';

const priorityClass: Record<TicketPriority, string> = { Low: 'bg-brand-light/40 text-stone-800 border border-brand-accent/40', Medium: 'bg-brand-olive/20 text-stone-900 border border-brand-olive/40', High: 'bg-brand-wine/10 text-brand-wine border border-brand-wine/30' };
const sentimentClass: Record<TicketSentiment, string> = { Positive: 'bg-brand-light/40 text-stone-800 border border-brand-accent/40', Neutral: 'bg-brand-olive/20 text-stone-900 border border-brand-olive/40', Negative: 'bg-brand-wine/10 text-brand-wine border border-brand-wine/30' };

export function TicketTable({ tickets }: { tickets: Ticket[] }) {
  return <><div className="space-y-3 md:hidden">{tickets.map((ticket) => <TicketCard key={ticket.id} ticket={ticket} />)}</div><div className="hidden overflow-hidden rounded-lg border border-brand-earth/15 bg-white md:block"><table className="w-full text-left text-sm"><thead className="border-b border-brand-earth/10 bg-brand-surface text-xs uppercase tracking-wider text-stone-500"><tr><th className="px-5 py-4 font-semibold">Ticket</th><th className="px-5 py-4 font-semibold">Cliente</th><th className="px-5 py-4 font-semibold">Estado</th><th className="px-5 py-4 font-semibold">Prioridad</th><th className="px-5 py-4 font-semibold">Sentimiento</th><th className="px-5 py-4" /></tr></thead><tbody className="divide-y divide-stone-100">{tickets.map((ticket) => <tr key={ticket.id} className="transition-colors hover:bg-brand-surface/70"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-brand-light/50 text-sm font-bold text-brand-wine">{ticket.type[0]}</span><div><p className="font-mono text-xs text-stone-400">{ticket.trackingNumber}</p><p className="mt-1 font-semibold text-stone-900">{ticket.subject}</p></div></div></td><td className="px-5 py-4 text-stone-600">{ticket.customerName}</td><td className="px-5 py-4"><span className="rounded-full border border-stone-200 px-2.5 py-1 text-xs text-stone-600">{ticket.status}</span></td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${priorityClass[ticket.priority]}`}>{ticket.priority}</span></td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${sentimentClass[ticket.sentiment]}`}>{ticket.sentiment}</span></td><td className="px-5 py-4 text-right"><button className="rounded-lg p-2 text-stone-400 hover:bg-brand-light/30 hover:text-brand-wine" aria-label={`Abrir ${ticket.trackingNumber}`}><ArrowUpRight size={17} /></button></td></tr>)}</tbody></table></div></>;
}
